### ISSUE TITLE
back translator missing

### ISSUE THREAD

**Issue by Rudzik** [mutalyzer/website#17]
I found this feature to be really a great addition to the Mutalyzer software and I have used it a lot, since many publications do not have nucleotide annotation, and only protein annotation. Now GUI does not have the back translator anymore, you can only find it in the API tab. Could you bring it back?

**Comment by jfjlaros** [comment]
This functionality is now part of the [Normalizer](https://mutalyzer.nl/normalizer). The back translated description shows up in the "Back translated description" fold whenever a back translation can be done.

Please find an example [here](https://mutalyzer.nl/normalizer/GRCh38(NP_002993.1):p.(Asp92Tyr)).

Note that "bare" protein identifiers (e.g., `NP_002993.1`) are not supported at the moment. This is on our to do list.

**Comment by Rudzik** [comment]
Thank you for your quick response.
What if I don't know NC and NG?
I would like to enter only NM, as previously.
 
Best regards,
Anna
 
W dniu 2022-12-02 11:43:55 użytkownik Jeroen F.J. Laros ***@***.***> napisał:
 
This functionality is now part of the Normalizer. The back translated description shows up in the "Back translated description" fold whenever a back translation can be done.
Please find an example here.
Note that "bare" protein identifiers (e.g., NP_002993.1) are not supported at the moment. This is on our to do list.

**Comment by jfjlaros** [comment]
> What if I don't know NC and NG?

Please note that no NC or NG was provided as input. Only a reference build (in this case GRCh38) was provided.

I presume you would like to use one of the following descriptions as input?

- `NP_002993.1:p.Asp92Tyr`
- `NM_003002.4:p.Asp92Tyr`

None of these are currently accepted by Mutalyzer 3. I opened a new issue (#18) for this.

**Comment by Rudzik** [comment]
Exactly, I normally used to put in NM_003002.4:p.Asp92Tyr. Thank you very much!

**Comment by jfjlaros** [comment]
This issue has been addressed [here](https://github.com/mutalyzer/mutalyzer/commit/5199c7f131034491a698c37de80b6cd945fb6082). Mutalyzer is now able to backtranslate the following descriptions:

- [`NP_002993.1:p.Asp92Tyr`](https://mutalyzer.nl/normalizer/NP_002993.1:p.Asp92Tyr)
- [`NM_003002.4:p.Asp92Tyr`](https://mutalyzer.nl/normalizer/NM_003002.4:p.Asp92Tyr)
