### ISSUE TITLE
hgvs not loading on https://mutalyzer.nl/normalizer

### ISSUE THREAD

**Issue by cathtyner** [mutalyzer/website#34]
Hi all, 

When I try to load an hgvs, e.g., 
https://mutalyzer.nl/normalizer/NG_012337.3(NM_003002.4):c.274G%3ET
the page shows a spinning icon and never loads (i've waitied over 10 minutes). 
Mac Sonoma 14.1.2.
Chrome Version 120.0.6099.109 (Official Build) (x86_64)
Same issue on Firefox 120.0.1

**Comment by jfjlaros** [comment]
Thank you for reporting this issue.

I cannot reproduce this problem at this time. Can you confirm that this issue is cleared on your side too?

**Comment by cathtyner** [comment]
Seems to be resolved now, thank you!

**Comment by jfjlaros** [comment]
My guess is that the connection with the NCBI was down for a while.
