### ISSUE TITLE
GRCH37 for Normalizer

### ISSUE THREAD

**Issue by TeodoraTockovska** [mutalyzer/website#39]
Hi! I have used Mutalyzer 2.0 in the past ([Position Converter](https://v2.mutalyzer.nl/batch-jobs?job_type=position-converter)). Could you please add the Assembly feature to Normalizer (Mutalyzer 3.0)? I would like to use Mutalyzer 3 for my tasks but I can't because it lacks the ability to select an assembly (I require GRCh37 assembly). 

Since the web application of Mutalyzer 3 searches 1 variant at a time, I assume the best way to submit a list of variants is to use the API. I recommend improving the documentation for the API (specifically adding descriptions for the parameters).

Thanks.

**Comment by jfjlaros** [comment]
> I would like to use Mutalyzer 3 for my tasks but I can't because it lacks the ability to select an assembly

The normalizer accepts the following (unofficial) syntax to select a transcript from an assembly:
[`GRCh37(NM_003002.4):c.274del`](https://mutalyzer.nl/normalizer/GRCh37(NM_003002.4):c.274del)
which leads us to the genomic description `NC_000011.9:g.111959695del`.

Additionally, the following (also unofficial) syntax can be used to select a chromosome:
[`GRCh37(chr11):g.111959695del`](https://mutalyzer.nl/normalizer/GRCh37(chr11):g.111959695del)
which leads us (amongst others) to the transcript description `NC_000011.9(NM_003002.4):c.274del`.

Is this what you need?

>  I assume the best way to submit a list of variants is to use the API.

That, or you can use the [Batch Processor](https://mutalyzer.nl/batchprocessor).

> I recommend improving the documentation for the API

I fully agree.

**Comment by TeodoraTockovska** [comment]
@jfjlaros Thank you for your response, those tips are very helpful!
