### ISSUE TITLE
Protein predicted from variant coding sequence

### ISSUE THREAD

**Issue by lairdr** [mutalyzer/website#42]
Protein predicted from variant coding sequence is not clearly available in version 3.0.8 at this time, but can be visualised in archive v2.0.35. Is there a way to access this in v3 or do you intend to re-establish?

**Comment by mihailefter** [comment]
Could you please clarify? Are you referring to something beyond what is shown in the screenshot below?

![image](https://github.com/user-attachments/assets/fca54d2e-bb4e-4379-8d1e-ec0a93028d3c)

**Comment by lairdr** [comment]
Apologies, this was our error in using the tool.

Thanks
