### ISSUE TITLE
selecting result of normalizer in sequence mode

### ISSUE THREAD

**Issue by marksantcroos** [mutalyzer/website#7]
https://v3.mutalyzer.nl/namechecker/%5B2del;3_4AA%3EG%5D?only_variants=true&sequence=AAAA

Selecting the resulting `2_4delinsG` gives an error as it is interpreted as a full description.

**Comment by mihailefter** [comment]
![image](https://user-images.githubusercontent.com/21262869/146051186-8045ba65-72a0-4a23-8a14-8bbb909f94d1.png)
